import type { PropDef } from "./PropsPanel";

export interface StoryConfig {
  id: string;
  name: string;
  category: string;
  component: string;
  description: string;
  propDefs: PropDef[];
  defaultProps: Record<string, any>;
}

export const stories: StoryConfig[] = [
  {
    id: "hero-cinematic-nav",
    name: "Cinematic Nav",
    category: "Heroes",
    component: "HeroCinematicNav",
    description:
      "Premium dark editorial hero with a particle sphere that assembles from scattered dots into a formed sphere via pseudo-scroll (wheel events). 18,000 particles use GLSL shaders with fibonacci-distributed sphere positions, staggered per-particle easing, noise displacement, and additive blending in warm orange/amber tones. Floating pill navbar with diamond markers, animated underline hovers, bottom-anchored headline, social pills, and soft-inversion CTA.",
    propDefs: [
      { name: "brandName", type: "string", defaultValue: "AETHON.STUDIO", description: "Logo text in the floating navbar" },
      { name: "headlineLine1", type: "string", defaultValue: "DESIGN", description: "Headline line 1 (bold uppercase)" },
      { name: "headlineLine2", type: "string", defaultValue: "BEYOND THE", description: "Headline line 2" },
      { name: "headlineLine3", type: "string", defaultValue: "SURFACE", description: "Headline line 3" },
      { name: "descriptorText", type: "string", defaultValue: "WE BUILD DIGITAL PRODUCTS\nOF ANY COMPLEXITY —\nFROM CONCEPT TO LAUNCH", description: "Small descriptor block (bottom-right)" },
      { name: "ctaText", type: "string", defaultValue: "START PROJECT", description: "Primary CTA button text" },
      { name: "scrollHintLabel", type: "string", defaultValue: "SCROLL", description: "Scroll hint label" },
      { name: "colorCore", type: "color", defaultValue: "#ff8800", description: "Core glow color of the particles" },
      { name: "colorOuter", type: "color", defaultValue: "#cc3300", description: "Outer color of the particles" },
      { name: "particleCount", type: "number", defaultValue: 18000, description: "Total number of particles (1000–50000)" },
      { name: "sphereRadius", type: "number", defaultValue: 1.35, description: "Radius of the target sphere (0.5–3.0)" },
      { name: "particleSize", type: "number", defaultValue: 28, description: "Base point size of each particle (5–80)" },
      { name: "rotationSpeed", type: "number", defaultValue: 0.08, description: "Y-axis rotation speed (0–0.5)" },
      { name: "noiseStrength", type: "number", defaultValue: 0.18, description: "Simplex noise displacement amplitude (0–1.0)" },
      { name: "floatAmplitude", type: "number", defaultValue: 0.08, description: "Scatter float/bob amplitude (0–0.5)" },
      { name: "assemblySmoothing", type: "number", defaultValue: 0.05, description: "Lerp factor for assembly progress (0.01–0.2)" },
      { name: "bgColor", type: "color", defaultValue: "#2a0800", description: "Base color for the radial background gradient" },
    ],
    defaultProps: {
      brandName: "AETHON.STUDIO",
      headlineLine1: "DESIGN",
      headlineLine2: "BEYOND THE",
      headlineLine3: "SURFACE",
      descriptorText: "WE BUILD DIGITAL PRODUCTS\nOF ANY COMPLEXITY —\nFROM CONCEPT TO LAUNCH",
      ctaText: "START PROJECT",
      scrollHintLabel: "SCROLL",
      colorCore: "#ff8800",
      colorOuter: "#cc3300",
      particleCount: 18000,
      sphereRadius: 1.35,
      particleSize: 28,
      rotationSpeed: 0.08,
      noiseStrength: 0.18,
      floatAmplitude: 0.08,
      assemblySmoothing: 0.05,
      bgColor: "#2a0800",
    },
  },
  {
    id: "nav-glass-pill",
    name: "Glass Pill",
    category: "Navigation",
    component: "NavGlassPill",
    description:
      "Floating pill-shaped navigation bar with glassmorphism backdrop blur, configurable opacity and colors. Features animated link hovers (underline / highlight / slide styles), responsive hamburger menu with staggered entrance animation, optional CTA button with accent glow, and sticky scroll shadow.",
    propDefs: [
      { name: "brandName", type: "string", defaultValue: "STUDIO", description: "Logo / brand text on the left" },
      { name: "ctaText", type: "string", defaultValue: "Get Started", description: "CTA button label" },
      { name: "ctaHref", type: "string", defaultValue: "#contact", description: "CTA button link href" },
      { name: "showCta", type: "boolean", defaultValue: true, description: "Show / hide CTA button" },
      { name: "sticky", type: "boolean", defaultValue: true, description: "Sticky positioning on scroll" },
      { name: "animationStyle", type: "select", defaultValue: "underline", options: ["underline", "highlight", "slide"], description: "Link hover animation variant" },
      { name: "bgColor", type: "color", defaultValue: "#0f0f16", description: "Background color of the pill" },
      { name: "bgOpacity", type: "number", defaultValue: 0.65, description: "Background opacity (0–1)" },
      { name: "accentColor", type: "color", defaultValue: "#6366f1", description: "Accent color for CTA and hover effects" },
      { name: "textColor", type: "color", defaultValue: "#ffffff", description: "Text color for brand, links, and icons" },
      { name: "blurAmount", type: "number", defaultValue: 20, description: "Backdrop blur amount in px (0–40)" },
      { name: "borderOpacity", type: "number", defaultValue: 0.08, description: "Border opacity (0–0.3)" },
      { name: "maxWidth", type: "number", defaultValue: 860, description: "Max width of the pill container (px)" },
      { name: "height", type: "number", defaultValue: 52, description: "Height of the pill bar (px)" },
      { name: "borderRadius", type: "number", defaultValue: 50, description: "Border radius of the pill (px)" },
    ],
    defaultProps: {
      brandName: "STUDIO",
      ctaText: "Get Started",
      ctaHref: "#contact",
      showCta: true,
      sticky: true,
      animationStyle: "underline",
      bgColor: "#0f0f16",
      bgOpacity: 0.65,
      accentColor: "#6366f1",
      textColor: "#ffffff",
      blurAmount: 20,
      borderOpacity: 0.08,
      maxWidth: 860,
      height: 52,
      borderRadius: 50,
    },
  },
  {
    id: "nav-brutalist-hybrid",
    name: "Brutalist Hybrid",
    category: "Navigation",
    component: "NavBrutalistHybrid",
    description:
      "Minimal brutalist navbar as a centered pill card with a hybrid navigation system: compact top bar with primary links and hamburger, plus a centered dropdown panel (not fullscreen) with all links. Features diamond/circle bullet markers, staggered link entrance animations, hamburger→X morph transition, scroll-aware pill opacity, and panel footer for social/contact links.",
    propDefs: [
      { name: "brandName", type: "string", defaultValue: "IZUM.STUDY", description: "Logo wordmark text (uppercase)" },
      { name: "brandIcon", type: "boolean", defaultValue: true, description: "Show 3-dot triangle icon before brand name" },
      { name: "showBullets", type: "boolean", defaultValue: true, description: "Show ◇/◦ markers before each link" },
      { name: "hoverStyle", type: "select", defaultValue: "underline-left", options: ["underline-left", "underline-center", "opacity"], description: "Top bar link hover animation" },
      { name: "pillBg", type: "color", defaultValue: "#1a1a1f", description: "Pill and panel background color" },
      { name: "textColor", type: "color", defaultValue: "#ffffff", description: "Global text color" },
      { name: "textOpacity", type: "number", defaultValue: 0.75, description: "Default link text opacity (0.3–1.0)" },
      { name: "overlayBg", type: "color", defaultValue: "#1a1a1f", description: "Dropdown panel background" },
      { name: "barHeight", type: "number", defaultValue: 48, description: "Top bar pill height in px (36–64)" },
      { name: "pillMaxWidth", type: "number", defaultValue: 620, description: "Max width of the pill and panel (px)" },
      { name: "pillRadius", type: "number", defaultValue: 8, description: "Border radius of pill and panel (px)" },
      { name: "overlayTextSize", type: "number", defaultValue: 20, description: "Panel menu link font size in px (14–32)" },
      { name: "linkSpacing", type: "number", defaultValue: 24, description: "Gap between top bar links in px (16–48)" },
      { name: "scrambleSpeed", type: "number", defaultValue: 35, description: "Text scramble interval in ms (20–80)" },
    ],
    defaultProps: {
      brandName: "IZUM.STUDY",
      brandIcon: true,
      showBullets: true,
      hoverStyle: "underline-left",
      pillBg: "#1a1a1f",
      textColor: "#ffffff",
      textOpacity: 0.75,
      overlayBg: "#1a1a1f",
      barHeight: 48,
      pillMaxWidth: 620,
      pillRadius: 8,
      overlayTextSize: 20,
      linkSpacing: 24,
      scrambleSpeed: 35,
    },
  },
];
